### ISSUE TITLE
Why MANIFEST.json is indexing some reference files as tests?

### ISSUE THREAD

**Issue by youennf** [w3c/web-platform-tests#2351] opened 2015-11-17 15:24 UTC
MANIFEST.json is indexing some reference files as tests, for instance in html/semantics/grouping-content/the-ol-element and html/dom/elements/global-attributes.

I would expect these files to not be considered as tests.

Should the tooling (or the reference files) be updated to not index them as tests?

**Comment by jdm** [comment] 2015-11-17 15:53
This is usually caused by files including script tags for testharness.js.

**Comment by jdm** [comment] 2015-11-17 15:54
Or if I misunderstood and it thinks they're reftests, then yes, the `<link rel=match>` elements cause that.

**Comment by gsnedders** [comment] 2015-11-17 15:56
As mentioned in #2350, reference files can refer to other things, as it's how we express A == B == C. B is both a ref (for A) and a test (== C). http://testthewebforward.org/docs/reftests.html touches on this but really could be clearer.

**Comment by youennf** [comment] 2015-11-17 16:02
Some test cases (like html/dom/elements/global-attributes/dir_auto-isolate-ref.html) refer to themselves. They are also classified as test files.
Some cleaning-up might be useful.

**Comment by bobholt** [comment] 2017-05-26 13:48
I don't find any more self-referencing refs. Closing as resolved. Please reopen if not the case.

**Closed by bobholt** 2017-05-26 13:48 UTC
Labels: infra
