### ISSUE TITLE
Add support for full-duplex streaming

### ISSUE THREAD

**Issue by wpt-issue-mover** [w3c/web-platform-tests#8366] opened 2017-11-20 16:18 UTC
Originally posted as https://github.com/w3c/wptserve/issues/80 by @louiscryan on 25 Mar 2016, 19:49 UTC:

> @annevk
> @domenic
> 
> As discussed over on https://github.com/whatwg/fetch/issues/229 in order to validate the now formalized support for full-duplex streaming in the WHATWG Fetch API we need to be able to test it.
> 
> One suggestion is to use hyper-h2 and implement an HTTP2 capable server that can be used for testing.  @lukasa & @tbetbetbe might be able to help out with that.

**Comment by wpt-issue-mover** [comment] 2017-11-20 16:18
Originally posted as https://github.com/w3c/wptserve/issues/80#issuecomment-201485530 by @Lukasa on 25 Mar 2016, 20:36 UTC:

> There are some demonstrations of how to build a HTTP/2 capable server using hyper-h2 in [the docs](http://python-hyper.org/h2/en/latest/examples.html#example-servers). The most fully-featured one is the [example WSGI server](http://python-hyper.org/h2/en/latest/wsgi-example.html), though that contains a lot of extra detail around the WSGI-handling logic that would be irrelevant for this situation.
> 
> If more specific advice would be useful let me know. =)

**Comment by Hexcles** [comment] 2017-12-04 16:24
Duplicate of #7693

**Closed by Hexcles** 2017-12-04 16:24 UTC
Labels: infra, priority:backlog, wptserve
