### ISSUE TITLE
Add ability to specify tests that should not be run in parallel with other tests

### ISSUE THREAD

**Issue by garykac** [w3c/web-platform-tests#5970] opened 2017-05-17 23:00 UTC
I have a few tests[1] that are currently manual tests because they interact with a global resource (the system clipboard) and cannot be run at the same time or else they will interfere with each other. These tests could be automated other than the fact that they can't be run in parallel.

AFAICT, there is currently no way to specify that a set of tests [A, B, C, ...] cannot be run in parallel with each other.  Or, to specify that a test cannot be run in parallel with any other test.

[1] See https://codereview.chromium.org/2695593006/

**Comment by bobholt** [comment] 2017-05-19 14:47
I believe parallel running is by design. I would expect tests that require certain states to not depend on other tests, but to be discrete and have their own self-contained setup/teardown prior to running.

Thoughts @jgraham, @jugglinmike?

**Comment by jugglinmike** [comment] 2017-05-19 15:29
Here's the state of things currently: Asynchronous tests expressed with the
`async_test` function are run in parallel. If expressed using `promise_test`,
however, the tests are run in series. I think that running tests in series is
preferable, but that's secondary to consistency. Ideally, both API's should
behave the same way. I've opened gh-6002 to discuss the resolution.

...but @garykac wants to write tests today! In the mean time, Gary, you *could*
use `promise_test`, but I wouldn't recommend that as we may decide to unify the
two APIs to run in parallel. Two "future-proof" solutions that I can see are:

1. Use the `explicit_done` setting, then implement your own scheduling logic to define tests asynchronously. You can read [the `testharness.js` docs for more details on how this could be achieved](http://web-platform-tests.org/writing-tests/testharness-api.html) (fun if you like that sort of thing, but bug prone and distracting)
2. Define the tests across multiple files

I realize that neither of these alternatives is particularly appealing, which
is why I will be advocating for consistently executing asynchronous tests in
series. Depending on your schedule, it might be worth sitting tight for now; I
would personally like to resolve this by some time next week.

**Comment by jgraham** [comment] 2017-05-19 21:00
I doubt that it would be compatible to change the scheduling of existing tests; I would expect timeouts at the least, but probably also spurious results because tests would miss events that happen when other tests are running, and tests that  simply don't run because some other test fails in a blocking way.

Building your own test scheduling isn't that hard using the event system. For example add each test to an array and do something like

```
setup({explicit_done: true})
var pending = [];
[…]
add_completion_callback(() => {
  if (pending.length) {
    async_test(pending.shift());
  } else {
    done();
  }
})
```

**Comment by bobholt** [comment] 2017-10-04 11:47
Closing because a user-code solution to the issue was provided. Please reopen and comment if this needs to be looked at further.

**Closed by bobholt** 2017-10-04 11:47 UTC
Labels: infra
