### ISSUE TITLE
Remove webgl tests from web-platform-tests

### ISSUE THREAD

**Issue by zcorpan** [w3c/web-platform-tests#10995] opened 2018-05-14 18:48 UTC
https://github.com/w3c/web-platform-tests/pull/10760#issuecomment-388826747

> However we do plan to continue to develop the WebGL conformance tests in https://github.com/KhronosGroup/WebGL .

> I filed KhronosGroup/WebGL#2537 a while ago, so I think it'd be best if there weren't any WebGL tests in wpt.

cc @foolip @kenrussell @RafaelCintron

**Comment by foolip** [comment] 2018-05-15 10:38
Dupe of https://github.com/w3c/web-platform-tests/issues/8044, where "move" implies "remove".

**Closed by foolip** 2018-05-15 10:39 UTC
Labels: webgl
