### ISSUE TITLE
Proposal: being serious about OWNERS

### ISSUE THREAD

**Issue by annevk** [w3c/web-platform-tests#5063] opened 2017-03-07 10:59 UTC
At least for a large number of labels I'm involved with OWNERS ends up meaning "PING". I'd rather not be given the impression there are OWNERS that respond to issues within a reasonable time frame and review incoming PRs if there are in fact none.

I suggest we rename OWNERS to PING or perhaps PEERS and only allow up to a single OWNER for a label. That person can delegate but is ultimately responsible for making sure things are somewhat in okay shape.

**Comment by frivoal** [comment] 2017-04-06 06:53
Given that you cannot review your own tests, I'd prefer if there could be two owners rather than one (with one being primary if you care about a the buck stopping with a particular individual), but I agree that the current file is misnamed and should be changed to reflect what it actually does.

**Comment by annevk** [comment] 2017-04-06 07:12
I'm fine with deputy owners, but being able to hold someone accountable often does wonders.

**Comment by foolip** [comment] 2018-03-28 13:32
I'll call this a dupe of https://github.com/w3c/web-platform-tests/issues/9230, where we arrived at the conclusion that we should rename it to NOTIFY.

That's quite the opposite of being serious, and I don't know how to make the triage of any given label really work. I proposed something for a few labels on public-test-infra today, but I wonder if it'll fly:
https://lists.w3.org/Archives/Public/public-test-infra/2018JanMar/0013.html

**Closed by foolip** 2018-03-28 13:32 UTC
Labels: policy
