### ISSUE TITLE
Unable to test Keyboard event on Checkbox

### ISSUE THREAD

**Issue by shanmuga-m** [w3c/web-platform-tests#9062] opened 2018-01-17 05:51 UTC
Unable to test/check the toggling the state of a checkbox with they keyboard.

**Comment by foolip** [comment] 2018-01-17 12:49
@kereliuk, is there already a tracking issue for keyboard input, or is this it now?

**Comment by gsnedders** [comment] 2018-01-17 13:26
Duplicate of #7434.

**Closed by gsnedders** 2018-01-17 13:26 UTC
Labels: infra, priority:roadmap, type:untestable
