### ISSUE TITLE
dom/events/Event-dispatch-multiple-stopPropagation.html not spec-compliant?

### ISSUE THREAD

**Issue by cdumez** [w3c/web-platform-tests#3456] opened 2016-08-11 21:29 UTC
I was trying to investigate why dom/events/Event-dispatch-multiple-stopPropagation.html is failing in WebKit.

The test dispatches several times the same event. The event listener is calling evt.stopPropagation() we would set the stop propagation flag. As per the specification [1], I would expect that the later calls to dispatchEvent() do NOT execute the event listeners given that the stop propagation flag is set on the event.

I don't see anything in the specification that says we should reset the stop propagation flag, unless I am missing something.

Note that the test used to be under uievents/legacy-domevents-tests/approved/EventObject.multiple.dispatchEvent.html and used to create a new event every time.
However, it was later moved to dom/events/Event-dispatch-multiple-stopPropagation.html and refactored by @Ms2ger to reuse the same event for every dispatchEvent() call.

For some reason, this test is passing in Firefox. Therefore, either I missed something in the specification or Firefox does something that is not part of the DOM spec.

[1] https://dom.spec.whatwg.org/#concept-event-listener-invoke

**Comment by cdumez** [comment] 2016-08-11 21:30
@Ms2ger @annevk

**Comment by annevk** [comment] 2016-08-12 07:37
There's a long discussion here: https://github.com/whatwg/dom/issues/219. I don't think it matters much what we do, as long as we all agree to do the same thing...

**Comment by cdumez** [comment] 2016-08-12 14:08
I do not mind either way either. However, I don't think we should test a behavior that is not specified.

**Comment by domenic** [comment] 2016-08-19 20:49
I guess this is a dupe of https://github.com/w3c/web-platform-tests/issues/3084. And they are both fixed after @cdumez's https://github.com/w3c/web-platform-tests/pull/3469.

**Closed by domenic** 2016-08-19 20:49 UTC
