### ISSUE TITLE
'picture is inserted' test in relevant-mutations.html should expect a load event

### ISSUE THREAD

**Issue by jdm** [w3c/web-platform-tests#2466] opened 2016-01-11 19:34 UTC
https://html.spec.whatwg.org/multipage/embedded-content.html#relevant-mutations includes "the element's adopting steps are run". appendChild runs:
* https://dom.spec.whatwg.org/#dom-node-appendchild
* https://dom.spec.whatwg.org/#concept-node-append
* https://dom.spec.whatwg.org/#concept-node-pre-insert
* https://dom.spec.whatwg.org/#concept-node-adopt

That means that the adoption steps run unconditionally, so the test should expect a load event. @yoavweiss @zcorpan am I reading anything wrong here?

**Comment by zcorpan** [comment] 2016-01-11 21:00
Hmm, this may be a spec bug. The adopting steps part was intended to cover when `img` changes documents, not when it's moved around in the same document.

**Comment by zcorpan** [comment] 2016-01-20 10:35
Will be fixed in the spec by https://github.com/whatwg/dom/pull/151

Thanks!

**Closed by zcorpan** 2016-01-20 10:35 UTC
