### ISSUE TITLE
Reftests not working with Chrome

### ISSUE THREAD

**Issue by jgraham** [w3c/web-platform-tests#6986] opened 2017-08-23 16:30 UTC
Running reftests in Chome, I get:

```
^C^C^C 0:26.96 LOG: Thread-TestrunnerManager-1 INFO Starting runner
 0:27.46 TEST_START: Thread-TestrunnerManager-1 /2dcontext/drawing-images-to-the-canvas/drawimage_canvas_6.html
 0:27.46 LOG: Thread-TestrunnerManager-1 INFO Test requires OS-level window focus
 0:27.47 TEST_END: Thread-TestrunnerManager-1 ERROR, expected PASS
Traceback (most recent call last):
  File "/home/james/develop/web-platform-tests/tools/wptrunner/wptrunner/executors/base.py", line 156, in run_test
    result = self.do_test(test)
  File "/home/james/develop/web-platform-tests/tools/wptrunner/wptrunner/executors/executorselenium.py", line 232, in do_test
    self.protocol.webdriver.set_window_size(600, 600)
  File "/home/james/develop/web-platform-tests/_venv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 896, in set_window_size
    'windowHandle': windowHandle})
  File "/home/james/develop/web-platform-tests/_venv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "/home/james/develop/web-platform-tests/_venv/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: disconnected: unable to connect to renderer
  (Session info: chrome=62.0.3192.0)
  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Linux 4.10.0-32-generic x86_64)


 0:27.50 LOG: Thread-TestrunnerManager-1 WARNING u'log' (u'debug', {'message': 'Hanging up on Selenium session'})
 0:27.50 LOG: Thread-TestrunnerManager-1 WARNING u'runner_teardown' ()
```

So it seems like something is perhaps broken in Chromedriver.

**Comment by Hexcles** [comment] 2017-08-28 20:01
cc @JKereliuk

**Comment by foolip** [comment] 2017-09-12 15:08
@flackr, funny thing re our conversation yesterday, looks like reftests actually aren't working in the dashboard.

@bobholt, getting to the bottom of this seems critical to making the dashboard useful for rather large areas of the test suites, in particular in CSS. Probably most tests using ahem are reftests?

**Comment by foolip** [comment] 2017-09-12 15:09
> Probably most tests using ahem are reftests?

To elaborate: I feel like I'm missing something, if reftests are actually totally broken, how could you tell if the ahem fixes worked?

**Comment by bobholt** [comment] 2017-09-13 12:28
So far, this does look like a regression in ChromeDriver. There was a similar issue a couple of years ago: https://bugs.chromium.org/p/chromedriver/issues/detail?id=401 that (based on the comments) seemed to be resolved in 2.15 and regressed in 2.20. [There](https://bugs.chromium.org/p/chromedriver/issues/detail?id=1427&can=1&q=unable%20renderer&sort=-id&colspec=ID%20Status%20Pri%20Owner%20Summary) [are](https://bugs.chromium.org/p/chromedriver/issues/detail?id=1573&can=1&q=unable%20renderer&sort=-id&colspec=ID%20Status%20Pri%20Owner%20Summary) [other](https://bugs.chromium.org/p/chromedriver/issues/detail?id=1651&can=1&q=unable%20renderer&sort=-id&colspec=ID%20Status%20Pri%20Owner%20Summary) [similar](https://bugs.chromium.org/p/chromedriver/issues/detail?id=1694) [issues](https://bugs.chromium.org/p/chromedriver/issues/detail?id=1924) that don't seem to be resolved more than they suddenly start working again.

The original thread suggests that the error is caused by closing a popup window unexpectedly (to chromedriver). Some of the "fixes" to the issues above were to uninstall anitvirus software, which I assume might try to quickly close popups.

My thoughts are we either a) find a way to close the popup test window in a way that makes ChromeDriver happier, or b) do as suggested in the original issue thread, and catch and ignore the ChromeDriver error, which (according to that thread) has no impact other than not erroring out your tests.

**Comment by bobholt** [comment] 2017-09-13 12:29
@foolip: The Ahem issue would affect all of the browsers. This reftest issue only affects Chrome.

**Comment by JKereliuk** [comment] 2017-09-13 12:31
I'll take a look today and see if I can catch the error in ChromeDriver without causing any side effects

**Comment by JKereliuk** [comment] 2017-09-13 15:53
With the most recent ChromeDriver release (2.32.498513) I am getting:

 0:12.19 LOG: MainThread INFO Starting http server on web-platform.test:8001
 0:12.20 LOG: MainThread WARNING Init failed! You may need to modify your hosts file. Refer to README.md.
 0:12.24 PROCESS_OUTPUT: ProcessReader (pid:138446) Full command: /usr/local/google/home/kereliuk/web-platform-tests/_venv/bin/chromedriver --port=4444 --url-base=/ --log-path=driver.log
(pid:138446) "Starting ChromeDriver 2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351) on port 4444"
 0:12.24 PROCESS_OUTPUT: ProcessReader (pid:138446) "Only local connections are allowed."
 0:12.74 LOG: Thread-TestrunnerManager-1 INFO Starting runner
DEBUG:web-platform-tests:GET /testharness_runner.html
DEBUG:web-platform-tests:Found handler FileHandler
DEBUG:web-platform-tests:200 GET /testharness_runner.html (None) 0
DEBUG:web-platform-tests:GET /favicon.ico
DEBUG:web-platform-tests:Found handler FileHandler
DEBUG:web-platform-tests:404 GET /favicon.ico (http://web-platform.test:8000/testharness_runner.html) 0
 0:15.10 TEST_START: Thread-TestrunnerManager-1 /2dcontext/drawing-images-to-the-canvas/drawimage_canvas_6.html
 0:15.11 LOG: Thread-TestrunnerManager-1 INFO Test requires OS-level window focus
DEBUG:web-platform-tests:GET /2dcontext/drawing-images-to-the-canvas/drawimage_canvas_6.html
DEBUG:web-platform-tests:Found handler FileHandler
DEBUG:web-platform-tests:200 GET /2dcontext/drawing-images-to-the-canvas/drawimage_canvas_6.html (None) 0
DEBUG:web-platform-tests:GET /2dcontext/drawing-images-to-the-canvas/drawimage_canvas_6_ref.html
DEBUG:web-platform-tests:Found handler FileHandler
DEBUG:web-platform-tests:200 GET /2dcontext/drawing-images-to-the-canvas/drawimage_canvas_6_ref.html (None) 0
 0:15.95 TEST_END: Thread-TestrunnerManager-1 PASS
 0:15.95 LOG: Thread-TestrunnerManager-1 INFO Pausing until the browser exits

Where the browser just hangs until you close it manually (it does say it's successful after that though).

The ChromeDriver log is telling me that DevTools disconnects:

[3.713][INFO]: Waiting for pending navigations...
[3.714][INFO]: Done waiting for pending navigations. Status: ok
[14.321][INFO]: Waiting for pending navigations...
[14.329][INFO]: Done waiting for pending navigations. Status: disconnected: not connected to DevTools
[14.360][INFO]: RESPONSE ExecuteAsyncScript
[14.363][INFO]: COMMAND ExecuteAsyncScript {
   "args": [  ],
   "script": "",
   "sessionId": "f7edb88e491b02d42c108650f5bbf8c7"
}
[14.365][INFO]: RESPONSE ExecuteAsyncScript no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=61.0.3163.79)

Still not completely sure what is happening yet.

**Comment by jgraham** [comment] 2017-09-13 16:41
> 0:15.95 LOG: Thread-TestrunnerManager-1 INFO Pausing until the browser exits

That's the clue here :) If you run a single test the runner stops after the test by default for manual inspection of the browser state. Try `--no-pause-after-test`.

**Comment by JKereliuk** [comment] 2017-09-13 17:04
Thanks @jgraham !

I passed that in and am not getting any errors. Can someone confirm that this is still happening on the most recent version of ChromeDriver?

**Comment by jgraham** [comment] 2017-09-13 17:39
``james@ginny:~/develop/web-platform-tests$ ./wpt run chrome css/css-flexbox-1/flexbox_flow-column-wrap.html --no-pause
Using webdriver binary /home/james/develop/web-platform-tests/_venv/bin/chromedriver
 0:01.06 LOG: MainThread INFO Updating test manifest /home/james/develop/web-platform-tests/MANIFEST.json
 0:09.63 LOG: MainThread INFO Using 1 client processes
 0:09.69 LOG: MainThread INFO Starting http server on web-platform.test:8000
 0:09.70 SUITE_START: MainThread 1
 0:09.70 LOG: MainThread INFO Running reftest tests
 0:09.70 LOG: MainThread INFO Starting http server on web-platform.test:8001
 0:09.71 LOG: MainThread INFO Starting http server on web-platform.test:8443
 0:09.75 PROCESS_OUTPUT: ProcessReader (pid:5756) Full command: /home/james/develop/web-platform-tests/_venv/bin/chromedriver --port=4444 --url-base=/
(pid:5756) "Starting ChromeDriver 2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351) on port 4444"
 0:09.75 PROCESS_OUTPUT: ProcessReader (pid:5756) "Only local connections are allowed."
 0:10.24 LOG: Thread-TestrunnerManager-1 INFO Starting runner
 0:10.63 TEST_START: Thread-TestrunnerManager-1 /css/css-flexbox-1/flexbox_flow-column-wrap.html
 0:10.64 LOG: Thread-TestrunnerManager-1 INFO Test requires OS-level window focus
 0:10.64 TEST_END: Thread-TestrunnerManager-1 ERROR, expected PASS
Traceback (most recent call last):
  File "/home/james/develop/web-platform-tests/tools/wptrunner/wptrunner/executors/base.py", line 156, in run_test
    result = self.do_test(test)
  File "/home/james/develop/web-platform-tests/tools/wptrunner/wptrunner/executors/executorselenium.py", line 232, in do_test
    self.protocol.webdriver.set_window_size(600, 600)
  File "/home/james/develop/web-platform-tests/_venv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 944, in set_window_size
    'windowHandle': windowHandle})
  File "/home/james/develop/web-platform-tests/_venv/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 297, in execute
    self.error_handler.check_response(response)
  File "/home/james/develop/web-platform-tests/_venv/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: disconnected: unable to connect to renderer
  (Session info: chrome=62.0.3202.18)
  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 4.10.0-33-generic x86_64)


 0:10.64 LOG: Thread-TestrunnerManager-1 INFO No more tests
 0:10.66 LOG: Thread-TestrunnerManager-1 WARNING u'log' (u'debug', {'message': 'Hanging up on Selenium session'})
 0:10.66 LOG: Thread-TestrunnerManager-1 WARNING u'runner_teardown' ()
 0:10.66 LOG: MainThread INFO Running wdspec tests
 0:10.66 LOG: MainThread INFO No wdspec tests to run
 0:10.66 LOG: MainThread INFO Running testharness tests
 0:10.66 LOG: MainThread INFO No testharness tests to run
 0:10.66 LOG: MainThread INFO Got 1 unexpected results
 0:10.66 SUITE_END: MainThread 
Summary
=======

Ran 1 tests
Expected results: 0
Unexpected results: 1 (ERROR: 1)

Unexpected Results
==================

ERROR /css/css-flexbox-1/flexbox_flow-column-wrap.html
 0:10.77 LOG: MainThread INFO Closing logging queue
 0:10.77 LOG: MainThread INFO queue closed
```

Still seems to be failing here.

**Comment by JKereliuk** [comment] 2017-09-13 18:53
@jgraham 

What platform are you using? I am unable to reproduce this on my machine with the versions of ChromeDriver and Chome in your output.

**Comment by jgraham** [comment] 2017-09-14 11:03
This is on Linux.

**Comment by bobholt** [comment] 2017-09-14 11:43
I also still see the same errors on Linux.

```
(Session info: chrome=62.0.3202.18)
  (Driver info: chromedriver=2.32.498513 (2c63aa53b2c658de596ed550eb5267ec5967b351),platform=Linux 4.4.0-92-generic x86_64)
```

**Comment by JKereliuk** [comment] 2017-09-14 14:42
@jgraham @bobholt what version and distro of linux are you running? I am going to try and reproduce.

**Comment by jgraham** [comment] 2017-09-14 15:06
Ubuntu 17.04

**Comment by bobholt** [comment] 2017-09-14 15:08
@JKereliuk I'm using Mint 18.2, which is based off Ubuntu 16.04. 

The google cloud instances running results.web-platform-tests.org are running Debian 8.8.

TravisCI is currently running Ubuntu 14.04.

**Comment by foolip** [comment] 2017-09-19 09:10
@JKereliuk, any luck reproducing this? @gsnedders says it's a regression, and if it's a regression in ChromeDriver itself, then it should be a matter of bisecting, might be easier than understanding it by debugging.

**Comment by JKereliuk** [comment] 2017-09-19 15:32
Still haven't had luck reproducing :/ going to try using the Travis CI docker image. Once I'm able to reproduce I will bisect

**Comment by JKereliuk** [comment] 2017-09-19 21:15
I was able to reproduce. ChromeDriver is failing out on Set Window Size command. 
https://bugs.chromium.org/p/chromedriver/issues/detail?id=1918&can=1&q=Set%20Window%20size&colspec=ID%20Status%20Pri%20Owner%20Summary

This is the issue tracking the reason for the failure. It has been fixed and will be in the next release (I just checked and confirmed its working with reftests in WPT).

Moving forward, maybe I should update the Travis config so that it uses a ChromeDriver binary with the fix?

**Comment by foolip** [comment] 2017-09-19 21:49
What is the release schedule, when will an official ChromeDriver binary with this fix exist?

**Comment by JKereliuk** [comment] 2017-09-19 22:27
We aren't too formal with our release schedule, generally we do a release when we feel there is enough in it to justify (I think in the passed this turns out to be every 6 weeks ish).

We do try to commit to having complete support for the current stable release of chrome (not beta/dev/canary).

Next quarter we have a goal to formalize our release strategy a bit more :)

**Comment by Hexcles** [comment] 2017-09-19 22:34
> We do try to commit to having complete support for the current stable release of chrome (not beta/dev/canary).

In that case, it probably makes sense to release a new version ASAP as the current beta is about to become stable (and it's broken in current beta). Hence, we won't need to fiddle with Traivs configuration (assuming our Travis jobs always use the latest official release).

**Comment by jgraham** [comment] 2017-09-20 06:40
Yes, it tries to download the latest release for each run. If you could get a release out with this fix in that would be great.

**Comment by foolip** [comment] 2017-09-22 13:51
@JKereliuk, can we make a release whenever we want, or is there a release schedule to follow? Sooner is better :)

**Comment by JKereliuk** [comment] 2017-09-22 14:00
I'm talking to John Chen about this in a meeting later today, will report release plans later today :)

**Comment by JKereliuk** [comment] 2017-09-22 18:28
Current plan is to not release until closer to before the next stable chrome release. How much does this fix block the WPT infra?

**Comment by foolip** [comment] 2017-09-22 20:45
It is rather a big problem because all reftests are failing, that's thousands and thousands of tests.

Would it be possible to do a point release of the current stable ChromeDriver?

**Comment by gsnedders** [comment] 2017-09-23 14:37
This also makes it harder to convince people, especially in the CSS WG, to use wpt.fyi instead of their own custom tooling (relying on ad-hoc runs of the tests).

**Comment by JKereliuk** [comment] 2017-09-27 15:58
Hopefully this week there should be a release fixing this. Will keep plans updated :)

**Comment by JKereliuk** [comment] 2017-10-04 17:03
This should be fixed in the new release which is now available.

**Comment by bobholt** [comment] 2017-10-05 11:33
I've found one reftest in the pulls so far, and it looks like it's working in Chrome: https://travis-ci.org/w3c/web-platform-tests/jobs/283285046. That's promising. If we see others successfully complete, I think we can consider this done.

**Comment by bobholt** [comment] 2017-10-06 20:04
Finally got a good run out of wpt.fyi. It looks like reftests are working for sure.

Next week, we should take a look at the PRs and determine whether or not to move Chrome back to a CI required-pass.

**Closed by bobholt** 2017-10-06 20:04 UTC
Labels: infra, priority:roadmap

**Comment by foolip** [comment] 2017-10-09 12:01
Wow, this is cause for celebration. Thanks @JKereliuk!

**Comment by foolip** [comment] 2017-10-13 11:14
The cause for celebration is larger than I though. The pass rates in css/ are totally different now, Chrome is at 86% now, which means that the CSS tests aren't in as bad shape as it previously seemed. @tabatkins FYI.

My takeaway is that it's possible that a few small fixes can totally change the results, so getting wpt into good shape overall might not be as herculean a task as it seemed.
