### ISSUE TITLE
[eme] Expired license test fails with Widevine due to incorrect license

### ISSUE THREAD

**Issue by jrummell-chromium** [w3c/web-platform-tests#4026] opened 2016-10-19 20:23 UTC
The test https://www.w3c-test.org/encrypted-media/drm-mp4-playback-temporary-expired.html is failing on Chrome 56.0.2895.0 (latest canary build) with:
assert_approx_equals: expiration attribute should equal provided expiration time expected 1476901853505 +/- 2000 but got NaN

In investigating the reason for the failure, the license provided to update() contains a license that never expires, so returning NaN is correct.

I think that the license issued for this test needs to have a duration specified in order for the session expiration to be set.

**Comment by mwatson2** [comment] 2016-10-19 21:01
This is a regression. Plus the test is rather difficult to construct with the existing server support, where I often see clock skew and it rounds up the provided expiration time to (it's view of) the current time.

**Comment by mwatson2** [comment] 2016-10-19 21:09
I think PR #4028 should fix it but welcome your comments.

**Comment by ddorwin** [comment] 2016-10-21 19:07
@mwatson2, per the second paragraph of the original report, the issue appeared to be that the license was configured incorrectly such that it had no expiration, not that the expiration was incorrect. Do you think this is caused by a timing issue with the request?

**Comment by mwatson2** [comment] 2016-10-21 19:19
@ddorwin No, that was caused by the third parameter to the message handler being `expiration` when it should have been `{expiration: expiration}`. I forgot to update this file when moving from positional parameters to an object. This is fixed in the PR.

**Comment by ddorwin** [comment] 2016-10-21 19:53
Thanks for clarifying.

**Closed** 2016-10-25 15:06 UTC
Labels: encrypted-media
