### ISSUE TITLE
stability checker tries to run all testharness.js tests when testharness.js is modified

### ISSUE THREAD

**Issue by gsnedders** [w3c/web-platform-tests#10928] opened 2018-05-09 14:06 UTC
this invariably times out, @jgraham has apparently almost fixed this now

**Comment by foolip** [comment] 2018-05-09 14:14
I'd say this is a dupe of https://github.com/w3c/web-platform-tests/issues/7660. The right fix, IMHO, would be to have a CI which is able to run all testharness.js tests if testharness.js is modified, even if it doesn't do it by default.

**Closed** 2018-05-11 15:06 UTC
Labels: ci_stability, infra
