### ISSUE TITLE
There should be an equivalent of CSS2/syntax/uri-013.xht for CSS Syntax 3

### ISSUE THREAD

**Issue by upsuper** [w3c/web-platform-tests#6666] opened 2017-07-31 23:13 UTC
The expectation of `CSS2/syntax/uri-013.xht` doesn't match what the CSS Syntax 3 says. Specifically, this doesn't match how `<bad-url-token>` is handled, and that `url("string")` is handled as a function rather than `<url-token>`.

This test was probably originated from Gecko's internal reftest [layout/reftests/css-parsing/invalid-url-handling.xhtml](https://hg.mozilla.org/mozilla-central/file/87824406b9fe/layout/reftests/css-parsing/invalid-url-handling.xhtml). I'm updating that test to match the new spec in [Gecko bug 1383075](https://bugzilla.mozilla.org/show_bug.cgi?id=1383075).

We probably want to update that test, or create a new test for the behavior specified in CSS Syntax 3.

cc @dbaron

**Comment by gsnedders** [comment] 2017-08-01 13:17
Per policy, there shouldn't be any incompatibility between Level 2 and Level 3; this is therefore a bug (and we have an issue for this—[https://github.com/w3c/csswg-drafts/issues/412](w3c/csswg-drafts#412)—and there's a WG resolution that we need an errata for Level 2 and a change for the next revision of Level 2).

We should just update the test where it is.

**Comment by gsnedders** [comment] 2018-03-29 02:37
Just noticed this is a dupe of https://github.com/w3c/web-platform-tests/issues/5489.

**Closed by gsnedders** 2018-03-29 02:37 UTC
Labels: CSS2, wg-css
