### ISSUE TITLE
Stability checker does not recognize "multi-global" test modifications

### ISSUE THREAD

**Issue by annevk** [w3c/web-platform-tests#5130] opened 2017-03-13 16:20 UTC
https://github.com/w3c/web-platform-tests/pull/5129
https://travis-ci.org/w3c/web-platform-tests/jobs/210612033

Not entirely sure what the problem is here. @bobholt @jugglinmike

**Comment by jugglinmike** [comment] 2017-03-13 17:03
By the current configuration, TravisCI runs two identical builds for each
commit in a pull request. The error here is limited to just one of the two
"Chrome stability" jobs, and it describes a timeout after the instruction to
download information about the Chromedriver binary. In light of this, my
suspicion is that the error was caused by network instability. Do you mind if I
re-run the build to verify that it is not a recurring issue?

**Comment by annevk** [comment] 2017-03-13 17:10
Sure go ahead.

**Comment by jugglinmike** [comment] 2017-03-13 17:15
The manually-triggered build has passed:

https://travis-ci.org/w3c/web-platform-tests/jobs/210612033

Do you think it is safe to close this issue? I realize this is not a particularly satisfying resolution, but I don't see any indication of an error in the project's code.

**Comment by annevk** [comment] 2017-03-13 17:30
I think what we actually need to is to recognize the .any.js convention and run the corresponding .any.html and .any.worker.html tests. Same for the .worker.js convention. Would you mind of we reuse this issue for that?

**Comment by annevk** [comment] 2017-03-13 17:30
See http://web-platform-tests.org/writing-tests/testharness.html for the documentation of this feature by the way.

**Comment by jugglinmike** [comment] 2017-03-14 15:28
Works for me! Although this calls for a change in title...

**Comment by jugglinmike** [comment] 2017-03-28 14:45
Yesterday, @jgraham addressed this with the following patches: https://github.com/w3c/wpt-tools/pull/195 and https://github.com/w3c/wptrunner/pull/242. Because [the "stability checker" Python script installs the latest version of the `wptrunner` utility by invoking git from the command line](https://github.com/w3c/web-platform-tests/blob/8346b7f0dd01e2b68ed04c8039bd6a6da5417ce7/check_stability.py#L385-L390), no change to this repository is required.

**Closed by jugglinmike** 2017-03-28 14:45 UTC
Labels: infra
