### ISSUE TITLE
Make stability checker check for duplicate test names

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/web-platform-tests#4404] opened 2016-12-29 02:45 UTC
For the context, see https://github.com/w3c/web-platform-tests/pull/4402#issuecomment-269554805.

**Comment by jugglinmike** [comment] 2017-01-17 19:43
Test files with duplicate test names may cause confusion for humans as well. Am I overlooking some use case? Or might we resolve this by making the harness more strict (and correcting any errors this uncovers)?

**Comment by jugglinmike** [comment] 2017-01-17 22:09
[This condition is detected and reported by `testharnessreport.js`](https://github.com/w3c/testharness.js/blob/873f9680aff66553f84d38f21a038c4534cc2789/testharnessreport.js#L300-L302), so it's apparent to humans executing the test in a browser directly. It doesn't seem be be recognized by the web harness or the `wptrunner`, though. My plan is to investigate whether the current "harness-runner" protocol allows for communicating pass/fail status by some means other than specific sub-test failures.

**Comment by sideshowbarker** [comment] 2017-01-18 09:25
> Test files with duplicate test names may cause confusion for humans as well. Am I overlooking some use case?

No use case that I’m aware of.

**Comment by jgraham** [comment] 2017-01-18 09:36
My suggestion is to extend the result protocol not to change pass/fail, but to package up warnings, which we can log as warnings (or even as lint errors) from the python side and pick up using the handler in the stability checker script. So we would fail the stability check job if we got unstable results or any warnings from the test harness (although not any warnings in general).

**Comment by domenic** [comment] 2017-01-18 23:18
So, the stability checker already checks for this, just not in an intuitive way. At least, it checks for it when the tests are failing. It will tell you that the test is unstable because it failed 40/10 times (when there are 4 tests with the same name). You can see this in action in the Travis jobs for https://github.com/w3c/web-platform-tests/pull/4559.

**Comment by jugglinmike** [comment] 2017-01-18 23:53
(Just saw @domenic's updated comment, but I'll post my response anyway in case it helps others understand the motivation for the solution I have in mind.)

Yup, [the `is_inconsistent` function](https://github.com/w3c/web-platform-tests/blob/aae3e1b6ffb8b24acb777450933ceeafd97e3655/check_stability.py#L465-L466) covers two separate conditions: when there are multiple distinct status values and when the number of results is different than the number of iterations.

The problem is that the number of results is insufficient information to identify duplicated test names. That's because the number can also be effected by unstable test logic, making it possible (though unlikely) that duplicate tests are not identified when those same tests occasionally fail to execute at
all.

By enforcing this restriction at the protocol level (where the test environment can consistently identify duplication), we can both avoid confusion from duplicate test names and limit the sources of variability in the number of results.

**Comment by jgraham** [comment] 2017-04-06 18:04
@jugglinmike This is fixed, right?

**Comment by bobholt** [comment] 2017-05-26 15:40
Closing as resolved by https://github.com/w3c/testharness.js/pull/240.

**Closed by bobholt** 2017-05-26 15:40 UTC
Labels: ci_stability, infra
