### ISSUE TITLE
radio-groupname-case.html demands language specific tailoring

### ISSUE THREAD

**Issue by psdh** [w3c/web-platform-tests#2579] opened 2016-02-12 15:11 UTC
radio-groupname-case.html demands language specific tailoring at [line 22, 23](https://github.com/w3c/web-platform-tests/blob/master/html/semantics/forms/the-input-element/radio-groupname-case.html#L22-L23) while the [html spec](https://html.spec.whatwg.org/multipage/infrastructure.html#compatibility-caseless) says "no language-specific tailorings" and [Unicode's CaseFolding.txt](http://www.unicode.org/Public/UNIDATA/CaseFolding.txt) says about T "For non-Turkic languages, this mapping is normally not used."

**Comment by SimonSapin** [comment] 2016-02-12 15:18
This test is based on https://people.mozilla.org/~jdaggett/tests/radiobuttonnamecase.html

@nattokirai, is that file intended as “All `<input type=radio>` elements after a given `<pre>` element should be in the same group”, or is it just a collections of edge cases to watch out for?

My understanding of the spec as currently written is that Turkish İ and ı should not match with ASCII i.

**Comment by nattokirai** [comment] 2016-02-13 07:28
There were discussions in the CSSWG as to whether to use case-sensitive, ASCII-case-insensitive matching or some flavor of case-insensitive matching. The HTML5 spec requires "compatibility caseless matching" for radio group names. See the bug here:

https://www.w3.org/Bugs/Public/show_bug.cgi?id=16970

The specific Unicode algorithm referred to here is:

D146 (from Unicode 8.0, section 3.13):

A string X is a compatibility caseless match for a string Y if and only if:
  NFKD(toCasefold(NFKD(toCasefold(NFD(X))))) =
    NFKD(toCasefold(NFKD(toCasefold(NFD(Y))))) 

However, no user agent does this and that's what my testcase was designed to investigate. Instead, each UA seems to use some flavor of toLower(X) == toLower(Y) to do case-insensitive matching. The precise definition of which casefolding algorithm is used is typically some hybrid of various algorithms. The main difference is whether some form of decomposition is used and for which codepoints. Lots of adhocishness about this unfortunately.

So I guess the question is what should happen given the definition above. I wrote the original testcase simply to investigate what browsers were doing, so it may not be correct to assume that U+130 and U+131 should match.

**Comment by annevk** [comment] 2017-03-14 15:00
This was fixed in https://github.com/w3c/web-platform-tests/commit/2017bf80629423b21473a12948111b95f0477a30 and https://github.com/whatwg/html/pull/1941 by removing the case folding dependency.

**Closed by annevk** 2017-03-14 15:00 UTC
