### ISSUE TITLE
The instructions to run the server on Windows don't work

### ISSUE THREAD

**Issue by smaug----** [w3c/web-platform-tests#10108] opened 2018-03-20 10:24 UTC
I particular 
python wpt make-hosts-file >> %SystemRoot%\System32\drivers\etc\hosts 
seems to create some odd looking hosts file, with empty space between characters or something

**Comment by foolip** [comment] 2018-03-28 13:49
@thejohnjansen, I assume you've had some better luck with this, do you know what's missing from the docs?

**Comment by smaug----** [comment] 2018-03-28 14:41
Actually, I guess there is something wrong with the script. Since at least I got hosts file with
space between each character in domain names. Is the script creating utf16 output or something.

**Comment by gsnedders** [comment] 2018-05-02 17:15
Closing this as a dupe of #10741 given that's where I looked at it.

**Closed by gsnedders** 2018-05-02 17:15 UTC
Labels: docs, infra, priority:roadmap
